# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{isbn-tools}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kosuke Tanabe"]
  s.date = %q{2011-02-17}
  s.description = %q{Validate, convert and hyphenation of ISBN numbers}
  s.email = %q{}
  s.extra_rdoc_files = [
    "ChangeLog",
    "README",
    "TODO"
  ]
  s.files = [
    "ChangeLog",
    "LICENCE",
    "README",
    "Rakefile",
    "TODO",
    "VERSION",
    "data/ranges.dat",
    "lib/isbn/tools.rb",
    "tests/tc_isbn_tools_tests.rb"
  ]
  s.homepage = %q{http://isbn-tools.rubyforge.org}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{This library provides the ability to manipulate ISBN numbers}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

